Moraru no fire on base
7CavArma3Dev/7Cav-Alive-Altis pull request #138
Opened 2020-02-25 15:53 UTC by RaduM84

Extended "Fired" event handler for Players (initPlayerLocal.sqf) and Vehicles (respawnVehicleInitialized) to delete projectiles fired while within the "headquarters" marker.

2020-02-26 02:50 UTC, BojanOnTheInternet commented
Not 100% sure what's going on with this commit history and the diff here, but shits fucked yo. Can you try and get rid of all these extra files and avoid the merge conflicts?

2020-02-26 02:55 UTC, BojanOnTheInternet requested changes

2020-02-26 02:55 UTC, BojanOnTheInternet commented on 7Cav-Alive-WFW.Altis/scripts/vehicle/fn_respawnVehicleInitialize.sqf
> +
You don't need to have the code in both folders, the CI will copy any scripts over to the other mission files. We only need to edit scripts in the main Altis mission folder. You can leave this in, it'll just get overwritten.

2020-02-26 02:55 UTC, BojanOnTheInternet commented on 7Cav-Alive-WFW.Altis/initPlayerLocal.sqf
> +
See comment re: duplicate files below

2020-02-26 02:55 UTC, BojanOnTheInternet commented on 7Cav-Alive.Altis/initPlayerLocal.sqf
> +}];
Move

```
CLIENT_InitPlayerLocalComplete = true;
diag_log "initPlayerLocal end";
```

to end of file

2020-02-26 02:56 UTC, BojanOnTheInternet commented
Other than the above looks good to go 👌

2020-02-28 16:01 UTC, RaduM84 commented
I'll pull the newest branch and re-add my changes.

2020-03-16 04:07 UTC, davidcit646 commented
What're we doing with this?

2020-03-20 14:09 UTC, Jaidendude commented
@RaduM84 Give us an update please, else I'll close the pull request for now for being stale

2020-03-20 14:10 UTC, Jaidendude requested changes
Please provide an update.

2020-03-27 13:13 UTC, closed without merging